### ISSUE TITLE
Add option for multiple commits

### ISSUE THREAD

**Issue by JakeQuilty** [AndrewCopeland/git-manager#1]
```yaml
general:
  branch-name: add-CODEOWNERS
  pr-name: add CODEOWNERS file
  commits:
    - commit-message: add CODEOWNERS file 
      git-add:
        - CODEOWNERS
    - commit-message: add another file
      git-add:
        - more
        - files
```

Add a feature that processes commits after all changes have been made and adds/commits the files in batches following the config file
